/** Internal runtime defaults — not user-editable; no config file needed. */
export const DEFAULT_CONFIG = {
  locale: "pt-BR",
  port: 8770,
  dataDir: null,
  lm: {
    url: "http://127.0.0.1:1234/v1",
    model: null,
    modelDeep: null,
    modelEmbed: null,
    modelRerank: null,
    chatMaxTokens: 2048,
    chatMaxTokensDeep: 4096,
  },
  frames: {
    captureIntervalMs: 60000,
    captionIntervalMs: 60000,
    captionMaxTokens: 220,
    captionTemperature: 0.05,
    pipelineBatch: 2,
    jpegQuality: 12,
    size: "QVGA",
    staticSummary: "Sem movimento relevante.",
  },
  audio: {
    sampleRate: 16000,
    sttMaxAttempts: 3,
    sttTimeoutMs: 120000,
    sttLanguage: null,
    sttRejectPatterns: [
      "legendas pela comunidade",
      "legendas por ",
      "amara.org",
      "subtitles by",
      "subtitle by",
      "obrigado por assistir",
      "thanks for watching",
    ],
    retentionDays: 7,
    retentionSweepMs: 21600000,
    pipelineBatch: 4,
    vad: {
      frameMs: 1000,
      debounceMs: 300,
      silenceMs: 1200,
      prerollMs: 400,
    },
  },
  http: {
    bodyMaxBytes: 524288,
    ingestAudioMaxBytes: 131072,
    ingestFrameMaxBytes: 409600,
    ingestEventMaxBytes: 16384,
    configPatchMaxBytes: 65536,
  },
  pipeline: { enabled: true, intervalMs: 30000 },
  insights: {
    auto: true,
    intervalMs: 300000,
    temperature: 0.25,
    maxTokens: 2048,
    sampleUtterances: 24,
    sampleFrames: 12,
  },
  memory: {
    enabled: true,
    lookbackDays: 90,
    retrieveLimit: 14,
    minScore: 0.08,
    embedBatchSize: 32,
    minUtteranceChars: 12,
    utteranceGroupMs: 300000,
    contextQueryTemplate: "padrões entidades sons fala {day}",
    lexical: { minTokenLength: 3, stopWords: [] },
    rerank: { enabled: false, candidateLimit: 40, topK: 14 },
  },
  speaker: { minMatchScore: 0.82, maxEnrollmentSamples: 8 },
  entities: { soundKindEntity: {} },
  present: {
    hideStaticFrames: true,
    hidePendingInFeed: true,
    labels: {
      speechGroup: "Conversa",
      speechSingle: "Fala",
      soundPluralSuffix: "s",
      soundFallback: "Som",
      sceneGroup: "Cena contínua",
      sceneSingle: "Cena",
      pending: "Aguardando",
    },
  },
  perception: {
    motionForceMs: 300000,
    autoEnhance: true,
    storeSounds: true,
    soundEngine: "heuristic",
    soundLabels: {
      speech: "fala",
      bark: "latido",
      door: "porta",
      knock: "batida",
      appliance: "eletrodoméstico",
      unknown: "som",
    },
  },
  node: {
    brainUrl: null,
    wifiRetryMs: 5000,
    pushBackoffMaxMs: 30000,
    statusIntervalMs: 15000,
  },
};
