[platformio]
default_envs = spaceman-c3
extra_configs = platformio.local.ini

[secrets]
flags =

[env:spaceman-c3]
platform = espressif32 @ ^6.9.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -I include
    -DLV_CONF_SKIP=1
    -DLV_COLOR_DEPTH=16
    -DLV_USE_LOG=0
    -DLV_USE_STDLIB_MALLOC=LV_STDLIB_CLIB
    -DLV_DEF_REFR_PERIOD=20
    -DLV_USE_PERF_MONITOR=0
    -DLV_FONT_MONTSERRAT_10=1
    -DLV_FONT_MONTSERRAT_12=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_20=1
    -DLV_FONT_MONTSERRAT_28=1
    -DLV_USE_CHART=1
    -DLV_USE_ARC=1
    -DLV_USE_BAR=1
    -DDASH_FW_VERSION=\"2026.08.30-1\"
    ${secrets.flags}
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    bblanchon/ArduinoJson @ ^7.0.4
    lvgl/lvgl @ ^9.2.2
