import type { Theme } from "./types.js";

// Cores e estrutura vindas de boards/c3/dash/preview/mocks.html, na mesma ordem.
// `layout` e a familia que da a cada tema a forma que ele tinha no mock; sem
// isso os 30 viram 30 paletas com o mesmo desenho.

const std = { hero: 28, big: 20, body: 12, tag: 10, upper: true };

export const themes: Theme[] = [
  {
    ...std,
    id: "glass",
    name: "Glass",
    desc: "vidro sobre gradiente escuro",
    layout: "hero",
    bg: {
      kind: "gradient",
      from: "#141a2e",
      to: "#0b0e18",
      blobs: [{ x: 105, y: 25, r: 45, color: "#f59e0b", opa: 90 }],
    },
    fg: "#ffffff",
    muted: "#9aa3b8",
    accent: "#f59e0b",
    accent2: "#a78bfa",
    hot: "#fb7185",
    cold: "#60a5fa",
    good: "#34d399",
    bad: "#f87171",
    line: "#3c4a66",
    plate: "glass",
    plateColor: "#ffffff",
  },
  {
    ...std,
    id: "bento",
    name: "Bento grid",
    desc: "blocos de tamanhos diferentes, sem espaco morto",
    layout: "bento",
    bg: { kind: "solid", from: "#0e1117" },
    fg: "#ffffff",
    muted: "#7c88a1",
    accent: "#f59e0b",
    accent2: "#38bdf8",
    hot: "#f59e0b",
    cold: "#60a5fa",
    good: "#4ade80",
    bad: "#f87171",
    line: "#1f2937",
    plate: "solid",
    plateColor: "#1a2030",
  },
  {
    ...std,
    id: "brutal",
    name: "Neo-brutalist",
    desc: "borda grossa, sombra dura, cor chapada",
    layout: "cards",
    bg: { kind: "solid", from: "#fde047" },
    fg: "#000000",
    muted: "#3f3f16",
    accent: "#ffffff",
    accent2: "#f472b6",
    hot: "#dc2626",
    cold: "#22d3ee",
    good: "#16a34a",
    bad: "#dc2626",
    line: "#000000",
    plate: "outline",
    plateColor: "#000000",
  },
  {
    ...std,
    id: "terminal",
    name: "Terminal CRT",
    desc: "monoespacado verde sobre preto",
    layout: "rows",
    bg: { kind: "solid", from: "#050b05" },
    fg: "#86efac",
    muted: "#4ade80",
    accent: "#4ade80",
    accent2: "#a3e635",
    hot: "#fbbf24",
    cold: "#67e8f9",
    good: "#4ade80",
    bad: "#f87171",
    line: "#14532d",
    plate: "outline",
    plateColor: "#166534",
  },
  {
    ...std,
    id: "swiss",
    name: "Swiss tipografico",
    desc: "grade rigida, preto e vermelho, sem enfeite",
    layout: "swiss",
    bg: { kind: "solid", from: "#f4f4f0" },
    fg: "#111111",
    muted: "#111111",
    accent: "#dc2626",
    accent2: "#111111",
    hot: "#dc2626",
    cold: "#374151",
    good: "#15803d",
    bad: "#dc2626",
    line: "#111111",
    plate: "none",
    plateColor: "#111111",
  },
  {
    ...std,
    id: "neon",
    name: "Neon cyber",
    desc: "glow saturado sobre preto",
    layout: "hero",
    bg: {
      kind: "solid",
      from: "#07030f",
      blobs: [{ x: 64, y: 44, r: 46, color: "#c026d3", opa: 70 }],
    },
    fg: "#f0abfc",
    muted: "#67e8f9",
    accent: "#e879f9",
    accent2: "#22d3ee",
    hot: "#fda4af",
    cold: "#a5b4fc",
    good: "#4ade80",
    bad: "#fb7185",
    line: "#4c1d95",
    plate: "none",
    plateColor: "#c026d3",
  },
  {
    ...std,
    id: "eink",
    name: "E-ink minimal",
    desc: "fundo claro, tinta unica, muito respiro",
    layout: "swiss",
    bg: { kind: "solid", from: "#eceae4" },
    fg: "#1c1c1a",
    muted: "#5a5852",
    accent: "#1c1c1a",
    accent2: "#5a5852",
    hot: "#1c1c1a",
    cold: "#5a5852",
    good: "#1c1c1a",
    bad: "#1c1c1a",
    line: "#c9c6bd",
    plate: "none",
    plateColor: "#c9c6bd",
    upper: false,
  },
  {
    ...std,
    id: "lcd",
    name: "LCD Casio",
    desc: "digital retro, fundo esverdeado",
    layout: "rows",
    bg: { kind: "solid", from: "#c3d3a5" },
    fg: "#1f2a17",
    muted: "#3c4a32",
    accent: "#1f2a17",
    accent2: "#3c4a32",
    hot: "#7f1d1d",
    cold: "#1e3a8a",
    good: "#166534",
    bad: "#7f1d1d",
    line: "#1f2a17",
    plate: "outline",
    plateColor: "#1f2a17",
  },
  {
    ...std,
    id: "mesh",
    name: "Mesh gradient",
    desc: "fundo colorido continuo, texto branco",
    layout: "hero",
    bg: {
      kind: "solid",
      from: "#1e0a3c",
      blobs: [
        { x: 35, y: 35, r: 55, color: "#7c3aed", opa: 120 },
        { x: 110, y: 70, r: 50, color: "#ec4899", opa: 120 },
        { x: 55, y: 115, r: 45, color: "#06b6d4", opa: 110 },
      ],
    },
    fg: "#ffffff",
    muted: "#ddd6fe",
    accent: "#f472b6",
    accent2: "#22d3ee",
    hot: "#fb7185",
    cold: "#38bdf8",
    good: "#6ee7b7",
    bad: "#fda4af",
    line: "#5b21b6",
    plate: "glass",
    plateColor: "#ffffff",
  },
  {
    ...std,
    id: "dot",
    name: "Dot matrix",
    desc: "estilo Nothing, pontilhado",
    layout: "hero",
    bg: { kind: "dots", from: "#0a0a0a", line: "#242424", step: 4 },
    fg: "#ffffff",
    muted: "#888888",
    accent: "#dc2626",
    accent2: "#ffffff",
    hot: "#dc2626",
    cold: "#888888",
    good: "#ffffff",
    bad: "#dc2626",
    line: "#262626",
    plate: "none",
    plateColor: "#333333",
  },
  {
    ...std,
    id: "huge",
    name: "Numero gigante",
    desc: "o dado principal ocupa a tela toda",
    layout: "huge",
    bg: { kind: "solid", from: "#111827" },
    fg: "#f59e0b",
    muted: "#9ca3af",
    accent: "#f59e0b",
    accent2: "#60a5fa",
    hot: "#f97316",
    cold: "#60a5fa",
    good: "#34d399",
    bad: "#f87171",
    line: "#1f2937",
    plate: "none",
    plateColor: "#1f2937",
  },
  {
    ...std,
    id: "duotone",
    name: "Duotone diagonal",
    desc: "faixa colorida cortando o topo",
    layout: "cards",
    bg: { kind: "solid", from: "#0f172a" },
    fg: "#ffffff",
    muted: "#94a3b8",
    accent: "#f43f5e",
    accent2: "#38bdf8",
    hot: "#f43f5e",
    cold: "#38bdf8",
    good: "#4ade80",
    bad: "#f43f5e",
    line: "#334155",
    plate: "solid",
    plateColor: "#1e293b",
  },
  {
    ...std,
    id: "braun",
    name: "Braun / Rams",
    desc: "cinza tecnico, um unico acento laranja",
    layout: "cards",
    bg: { kind: "solid", from: "#d9d9d4" },
    fg: "#2b2b28",
    muted: "#5f5f58",
    accent: "#2b2b28",
    accent2: "#f97316",
    hot: "#f97316",
    cold: "#57534e",
    good: "#3f6212",
    bad: "#b91c1c",
    line: "#a8a8a0",
    plate: "solid",
    plateColor: "#c5c5bf",
  },
  {
    ...std,
    id: "arc",
    name: "Arco de foco",
    desc: "anel de progresso como elemento principal",
    layout: "arc",
    bg: { kind: "solid", from: "#0b1020" },
    fg: "#ffffff",
    muted: "#94a3b8",
    accent: "#f59e0b",
    accent2: "#38bdf8",
    hot: "#fb923c",
    cold: "#60a5fa",
    good: "#34d399",
    bad: "#f87171",
    line: "#1e293b",
    plate: "none",
    plateColor: "#1e293b",
  },
  {
    ...std,
    id: "aurora",
    name: "Aurora suave",
    desc: "verdes e azuis difusos, texto leve",
    layout: "hero",
    bg: {
      kind: "solid",
      from: "#04141a",
      blobs: [
        { x: 80, y: 20, r: 48, color: "#38bdf8", opa: 100 },
        { x: 45, y: 90, r: 55, color: "#10b981", opa: 110 },
      ],
    },
    fg: "#ecfeff",
    muted: "#a7f3d0",
    accent: "#bae6fd",
    accent2: "#38bdf8",
    hot: "#fbbf24",
    cold: "#67e8f9",
    good: "#34d399",
    bad: "#fda4af",
    line: "#134e4a",
    plate: "glass",
    plateColor: "#ffffff",
  },
  {
    ...std,
    id: "spec",
    name: "Ficha tecnica",
    desc: "denso, tabela de dados alinhada",
    layout: "rows",
    bg: { kind: "solid", from: "#0d1117" },
    fg: "#e5e7eb",
    muted: "#6b7280",
    accent: "#f59e0b",
    accent2: "#38bdf8",
    hot: "#f97316",
    cold: "#60a5fa",
    good: "#4ade80",
    bad: "#f87171",
    line: "#1f2937",
    plate: "none",
    plateColor: "#1f2937",
  },
  {
    ...std,
    id: "pixel",
    name: "Pixel 8-bit",
    desc: "fonte de bloco, paleta limitada",
    layout: "bento",
    bg: { kind: "solid", from: "#1a1c2c" },
    fg: "#ffcd75",
    muted: "#94b0c2",
    accent: "#ef7d57",
    accent2: "#41a6f6",
    hot: "#ef7d57",
    cold: "#41a6f6",
    good: "#38b764",
    bad: "#b13e53",
    line: "#333c57",
    plate: "solid",
    plateColor: "#333c57",
  },
  {
    ...std,
    id: "stack",
    name: "Cartao empilhado",
    desc: "cards sobrepostos com profundidade",
    layout: "cards",
    bg: { kind: "solid", from: "#111827" },
    fg: "#ffffff",
    muted: "#9ca3af",
    accent: "#2563eb",
    accent2: "#7c3aed",
    hot: "#f59e0b",
    cold: "#60a5fa",
    good: "#34d399",
    bad: "#f87171",
    line: "#374151",
    plate: "solid",
    plateColor: "#1f2937",
  },
  {
    ...std,
    id: "blueprint",
    name: "Blueprint",
    desc: "grade tecnica azul, tracos finos",
    layout: "rows",
    bg: { kind: "grid", from: "#0a2540", line: "#16456b", step: 8 },
    fg: "#7dd3fc",
    muted: "#38bdf8",
    accent: "#7dd3fc",
    accent2: "#a5f3fc",
    hot: "#fbbf24",
    cold: "#7dd3fc",
    good: "#4ade80",
    bad: "#fb7185",
    line: "#1e5f8e",
    plate: "outline",
    plateColor: "#38bdf8",
  },
  {
    ...std,
    id: "vapor",
    name: "Vaporwave",
    desc: "rosa e ciano, horizonte, grade",
    layout: "hero",
    bg: {
      kind: "gradient",
      from: "#2d1b4e",
      to: "#f472b6",
      blobs: [{ x: 64, y: 50, r: 30, color: "#fde047", opa: 200 }],
    },
    fg: "#ffffff",
    muted: "#fce7f3",
    accent: "#a5f3fc",
    accent2: "#22d3ee",
    hot: "#fb7185",
    cold: "#a5f3fc",
    good: "#86efac",
    bad: "#fb7185",
    line: "#db2777",
    plate: "glass",
    plateColor: "#ffffff",
  },
  {
    ...std,
    id: "material",
    name: "Material You",
    desc: "cantos muito arredondados, tonal",
    layout: "cards",
    bg: { kind: "solid", from: "#1b1b21" },
    fg: "#ffdfa0",
    muted: "#cac4d0",
    accent: "#4a4458",
    accent2: "#d0bcff",
    hot: "#ffb4ab",
    cold: "#a8c7fa",
    good: "#7fd8a0",
    bad: "#ffb4ab",
    line: "#4a4458",
    plate: "solid",
    plateColor: "#332d41",
  },
  {
    ...std,
    id: "oled",
    name: "Alto contraste OLED",
    desc: "preto puro, branco puro, um acento",
    layout: "hero",
    bg: { kind: "solid", from: "#000000" },
    fg: "#ffffff",
    muted: "#666666",
    accent: "#00e676",
    accent2: "#ffffff",
    hot: "#ff5252",
    cold: "#40c4ff",
    good: "#00e676",
    bad: "#ff5252",
    line: "#1a1a1a",
    plate: "none",
    plateColor: "#333333",
  },
  {
    ...std,
    id: "paper",
    name: "Jornal",
    desc: "manchete e fio horizontal",
    layout: "swiss",
    bg: { kind: "solid", from: "#f5f2e8" },
    fg: "#12100c",
    muted: "#57534e",
    accent: "#12100c",
    accent2: "#7f1d1d",
    hot: "#7f1d1d",
    cold: "#1e3a8a",
    good: "#166534",
    bad: "#7f1d1d",
    line: "#12100c",
    plate: "none",
    plateColor: "#12100c",
    upper: false,
  },
  {
    ...std,
    id: "neumorph",
    name: "Neumorphism",
    desc: "relevo suave, monocromatico",
    layout: "cards",
    bg: { kind: "solid", from: "#2a2d35" },
    fg: "#dfe3ec",
    muted: "#8b91a1",
    accent: "#363a44",
    accent2: "#7dd3fc",
    hot: "#fbbf24",
    cold: "#7dd3fc",
    good: "#6ee7b7",
    bad: "#fca5a5",
    line: "#1e2027",
    plate: "solid",
    plateColor: "#31343d",
  },
  {
    ...std,
    id: "split",
    name: "Split vertical",
    desc: "duas colunas, cor solida contra escuro",
    layout: "split",
    bg: { kind: "solid", from: "#0f172a" },
    fg: "#e2e8f0",
    muted: "#64748b",
    accent: "#0ea5e9",
    accent2: "#bae6fd",
    hot: "#fb923c",
    cold: "#7dd3fc",
    good: "#4ade80",
    bad: "#f87171",
    line: "#1e293b",
    plate: "solid",
    plateColor: "#1e293b",
  },
  {
    ...std,
    id: "bars",
    name: "Barras de dados",
    desc: "cada metrica vira uma barra",
    layout: "bars",
    bg: { kind: "solid", from: "#101418" },
    fg: "#ffffff",
    muted: "#7d8794",
    accent: "#f59e0b",
    accent2: "#818cf8",
    hot: "#f59e0b",
    cold: "#38bdf8",
    good: "#4ade80",
    bad: "#f87171",
    line: "#1e262e",
    plate: "none",
    plateColor: "#1e262e",
  },
  {
    ...std,
    id: "sticker",
    name: "Sticker pop",
    desc: "formas coloridas sobrepostas",
    layout: "cards",
    bg: {
      kind: "solid",
      from: "#fef3c7",
      blobs: [
        { x: 20, y: 20, r: 36, color: "#fb7185", opa: 230 },
        { x: 114, y: 94, r: 36, color: "#38bdf8", opa: 230 },
      ],
    },
    fg: "#111111",
    muted: "#57534e",
    accent: "#ffffff",
    accent2: "#38bdf8",
    hot: "#fb7185",
    cold: "#38bdf8",
    good: "#16a34a",
    bad: "#e11d48",
    line: "#111111",
    plate: "outline",
    plateColor: "#ffffff",
  },
  {
    ...std,
    id: "metric",
    name: "Monoespaco metrico",
    desc: "tudo alinhado, tipo painel de carro",
    layout: "hero",
    bg: { kind: "solid", from: "#14161a" },
    fg: "#e2e8f0",
    muted: "#64748b",
    accent: "#22d3ee",
    accent2: "#94a3b8",
    hot: "#fb923c",
    cold: "#22d3ee",
    good: "#4ade80",
    bad: "#f87171",
    line: "#1e293b",
    plate: "none",
    plateColor: "#1e293b",
  },
  {
    ...std,
    id: "frame",
    name: "Moldura fina",
    desc: "borda de 1px, conteudo com respiro",
    layout: "hero",
    bg: { kind: "solid", from: "#0c0f16" },
    fg: "#f8fafc",
    muted: "#64748b",
    accent: "#f59e0b",
    accent2: "#94a3b8",
    hot: "#fb923c",
    cold: "#60a5fa",
    good: "#34d399",
    bad: "#f87171",
    line: "#2b3446",
    plate: "outline",
    plateColor: "#2b3446",
  },
  {
    ...std,
    id: "halfmoon",
    name: "Meia-lua",
    desc: "faixa curva colorida no topo",
    layout: "hero",
    bg: {
      kind: "solid",
      from: "#0b1120",
      blobs: [{ x: 64, y: -6, r: 66, color: "#f97316", opa: 240 }],
    },
    fg: "#ffffff",
    muted: "#94a3b8",
    accent: "#fdba74",
    accent2: "#38bdf8",
    hot: "#f97316",
    cold: "#60a5fa",
    good: "#4ade80",
    bad: "#f87171",
    line: "#1e293b",
    plate: "solid",
    plateColor: "#111c33",
  },
];

export const themeById = (id: string): Theme => themes.find((t) => t.id === id) ?? themes[0]!;
