[platformio]
default_envs = goouuu-s3-cam

[env:goouuu-s3-cam]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0
    -I include
    -DWIFI_SSID=\"SUA_REDE_WIFI\"
    -DWIFI_PASS=\"SUA_SENHA_WIFI\"
    -DFOLIO_BRAIN_URL=\"http://192.168.1.100:8770\"
    -DFOLIO_DEVICE_ID=\"folio-s3-01\"
build_unflags =
    -DARDUINO_USB_MODE=1
monitor_rts = 0
monitor_dtr = 0
lib_deps =
    espressif/esp32-camera @ ^2.0.4
