export { DB_SCHEMA, LEGACY_TABLES } from "./schema.mjs";
export { sqlText, sqlNullable } from "./sql.mjs";
export { migrateSchemaV2, migrateDb, openDb } from "./connection.mjs";
export { ensureDevice, touchDevice, listDevices } from "./devices.mjs";
export { listSpeakers, getSpeaker, upsertSpeaker, updateSpeakerProfile, speakersWithFingerprint } from "./speakers.mjs";
export { listEntities, getEntity, entityBySpeakerId, speakerEntityId, ensureSpeakerEntity, upsertEntity, patchEntityPatterns, entitiesActiveOnDay } from "./entities.mjs";
export { clearAudioChunkPath, insertAudioChunk, pendingAudioChunks, markAudioProcessed, updateAudioClassification, bumpSttAttempts, deleteAudioChunk, pruneExpiredPcm } from "./audio.mjs";
export { insertUtterance, getAudioChunk, audioChunksForDay, utterancesForDay } from "./utterances.mjs";
export { insertFrame, pendingFrames, markFrameProcessed, getFrame, lastProcessedFrame, framesForDay } from "./frames.mjs";
export { insertEvent, eventsForDay, pendingCounts } from "./events.mjs";
export { getDayInsights, upsertDayInsights, dayInsightDays, latestInsightUpdate, witnessIndexedAt, memoryEvidenceSet } from "./daily.mjs";
export { deleteMemoryForDay, insertMemoryChunk, memoryChunksInRange, memoryChunkCount, memoryChunksForEntity, profileFactsFromMemory } from "./memory.mjs";
export { witnessStats, latestWitnessAt, alignedMomentsForDay, timelineForDay } from "./timeline.mjs";
